from django.urls import path
from .views import *
from .query_essential import *
from .result import result
from .test_essential import test_essential

urlpatterns = [
    path('home_page/', home_page),
    path('4000_essential_english_words/', essential_english_words),
    path('error/', error),
    path('settings/', settings),
    path('about/', about),
    path('play_again/', play_again),

    path('query_essential_1/', query_essential_1),
    path('query_essential_2/', query_essential_2),
    path('query_essential_3/', query_essential_3),

    path('test_essential/', test_essential),
    path('result/', result)
]
"""
>>LIST ga ma'lumot qo'shish:
amount_instance = Amount.objects.get(id=1)
amount_instance.error = [1, 2, 3] # ma'lumotni qo'shish
amount_instance.save() #

>>LIST ma'lumotini o'qish:
amount_instance = Amount.objects.get(id=1)
my_error_list = amount_instance.error
print(my_error_list[0])

>>Yo'q manzilga so'rov yuborilsa:
def custom_404(request, exception):
    # do something
    return render(request, '404.html', status=404)
"""


"""  <<<<<<<< Keyinchalik o'qishim kerak >>>>>>

Django settings for word project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""