# Generated by Django 4.2 on 2023-05-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('unit', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Soz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.word')),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_number', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.PositiveSmallIntegerField(default=2)),
                ('from_unit', models.PositiveSmallIntegerField(default=1)),
                ('to_unit', models.PositiveSmallIntegerField(default=2)),
                ('language', models.CharField(default='eng-uzb', max_length=10)),
                ('acceptance', models.PositiveSmallIntegerField(default=0)),
                ('question_soz', models.PositiveIntegerField(default=1)),
                ('profil', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
    ]
