# Generated by Django 4.2 on 2023-05-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='question_lar',
            field=models.CharField(default='{}', max_length=2010),
        ),
    ]
