# Generated by Django 4.2 on 2023-05-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_book_about_alter_word_soz_turkumi_and_more'),
    ]

