# Generated by Django 4.2 on 2023-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_amount_question_lar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='question_lar',
            field=models.CharField(default='[]', max_length=2010),
        ),
    ]
