# Generated by Django 4.2 on 2023-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_word_soz_turkumi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.PositiveSmallIntegerField(default=2)),
            ],
        ),
    ]
