# Generated by Django 4.2 on 2023-05-08 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='i',
            new_name='amount_number',
        ),
    ]
