# Generated by Django 4.2 on 2023-05-16 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_profil_last_login_profil_last_activity'),
        ('mainapp', '0004_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='book',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='amount',
            name='profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil'),
        ),
    ]
