# Generated by Django 4.2 on 2023-05-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_i_amount_amount_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='from_unit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amount',
            name='to_unit',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
