# Generated by Django 4.2 on 2023-05-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_amount_from_unit_amount_to_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='acceptance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amount',
            name='language',
            field=models.CharField(default='eng-uzb', max_length=10),
        ),
    ]
