# Generated by Django 4.2 on 2023-05-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('mainapp', '0008_amount_profil_amount_question_soz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='profil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.profil'),
        ),
    ]
