# Generated by Django 4.2 on 2023-05-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_amount_lamp_amount_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='error',
        ),
    ]
