# Generated by Django 4.2 on 2023-05-09 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7)),
                ('tel_number', models.CharField(blank=True, max_length=20, null=True)),
                ('year_of_birth', models.PositiveSmallIntegerField()),
                ('test', models.PositiveIntegerField(default=0)),
                ('acceptance', models.PositiveIntegerField(default=0)),
                ('rejection', models.PositiveIntegerField(default=0)),
                ('percentage', models.PositiveSmallIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
