# Generated by Django 4.2 on 2023-05-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
