# Generated by Django 4.2 on 2023-05-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_profil_level_amount_alter_profil_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='level_amount',
        ),
    ]
