# Generated by Django 4.2 on 2023-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_profil_level_remove_profil_level_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
