# Generated by Django 4.2 on 2023-05-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0006_remove_profil_last_login_profil_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_lar', models.CharField(default='[]', max_length=3010)),
                ('book', models.PositiveSmallIntegerField(default=1)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
            ],
        ),
    ]
